version: '3.8'

services:
  pubchempy-fastmcp-v3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # APT mirror configuration (comment out to use default)
        APT_MIRROR: ${APT_MIRROR:-http://mirrors.aliyun.com}
        # PIP mirror configuration (comment out to use default)
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST:-pypi.tuna.tsinghua.edu.cn}
    ports:
      - "8989:8989"  # FastMCP HTTP server port
    environment:
      - PYTHONPATH=/app
      - PORT=8989
      # Mirror configuration for runtime (if needed)
      - APT_MIRROR=${APT_MIRROR:-http://mirrors.aliyun.com}
      - PIP_INDEX_URL=${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
      - PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST:-pypi.tuna.tsinghua.edu.cn}
    volumes:
      - ./src:/app/src  # Hot reload: mount source code
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - fastmcp-network

networks:
  fastmcp-network:
    driver: bridge 