# Python 示例 - 论文搜索
import requests
import json

def search_papers(query, limit=10,offset=0):
    url = "https://lifuai.com/api/v1/graph/v1/paper/search"
    fields = 'paperId,title,abstract,venue,year,referenceCount,citationCount,influentialCitationCount,isOpenAccess,openAccessPdf,fieldsOfStudy,url,externalIds,tldr,publicationTypes,publicationDate,journal'
    params = {
        'query': query,
        'limit': limit,
        'offset': offset,
        'fields': fields
    }
    
    headers = {
        'Authorization': f'Bearer {api_key}',
        'Content-Type': 'application/json'
    }
    
    try:
        response = requests.get(url, params=params, headers=headers)
        response.raise_for_status()
        
        data = response.json()
        print(f"找到 {data['total']} 篇相关论文:")
        
        for paper in data['data']:
            print(json.dumps(paper, ensure_ascii=False, indent=4))
            
    except requests.exceptions.RequestException as e:
        print(f"请求失败: {e}")

# 使用示例
api_key = "sk-user-D499F926CD23FACD63C62D59E4038CCC"
search_papers("generative AI", limit=15)

"""
返回
{
    "paperId": "c713ade0d479355c8e155ca720fbe36c34e9e2f6",
    "externalIds": {
        "DOI": "10.1007/s40547-024-00143-4",
        "CorpusId": 268241341
    },
    "url": "https://www.semanticscholar.org/paper/c713ade0d479355c8e155ca720fbe36c34e9e2f6", 
    "title": "Sentiment Analysis in the Age of Generative AI",
    "venue": "Customer Needs and Solutions",
    "year": 2024,
    "referenceCount": 37,
    "citationCount": 85,
    "influentialCitationCount": 5,
    "isOpenAccess": true,
    "openAccessPdf": {
        "url": "https://link.springer.com/content/pdf/10.1007/s40547-024-00143-4.pdf",       
        "status": "HYBRID",
        "license": "CCBY",
        "disclaimer": "Notice: Paper or abstract available at https://api.unpaywall.org/v2/10.1007/s40547-024-00143-4?email=<INSERT_YOUR_EMAIL> or https://doi.org/10.1007/s40547-024-00143-4, which is subject to the license by the author or copyright owner provided with this content. Please go to the source to verify the license and copyright information for your use."  
    },
    "fieldsOfStudy": null,
    "tldr": {
        "model": "tldr@v2.0.0",
        "text": "A comprehensive exploration of LLMs’ proficiency in sentiment analysis, a core task in marketing research for understanding consumer emotions, opinions, and perceptions, finds that linguistic features such as the presence of lengthy, content-laden words improve classification performance, while other features such as single-sentence reviews and less structured social media text documents reduce performance."
    },
    "publicationTypes": [
        "JournalArticle",
        "Review"
    ],
    "publicationDate": "2024-03-05",
    "journal": {
        "name": "Customer Needs and Solutions",
        "pages": "1-19",
        "volume": "11"
    },
    "authors": [
        {
            "authorId": "2289954773",
            "name": "Jan Ole Krugmann"
        },
        {
            "authorId": "2289984482",
            "name": "Jochen Hartmann"
        }
    ],
    "abstract": "In the rapidly advancing age of Generative AI, Large Language Models (LLMs) such as ChatGPT stand at the forefront of disrupting marketing practice and research. This paper presents a comprehensive exploration of LLMs’ proficiency in sentiment analysis, a core task in marketing research for understanding consumer emotions, opinions, and perceptions. We benchmark the performance of three state-of-the-art LLMs, i.e., GPT-3.5, GPT-4, and Llama 2, against established, high-performing transfer learning models. Despite their zero-shot nature, our research reveals that LLMs can not only compete with but in some cases also surpass traditional transfer learning methods in terms of sentiment classification accuracy. We investigate the influence of textual data characteristics and analytical procedures on classification accuracy, shedding light on how data origin, text complexity, and prompting techniques impact LLM performance. We find that linguistic features such as the presence of lengthy, content-laden words improve classification performance, while other features such as single-sentence reviews and less structured social media text documents reduce performance. Further, we explore the explainability of sentiment classifications generated by LLMs. The findings indicate that LLMs, especially Llama 2, offer remarkable classification explanations, highlighting their advanced human-like reasoning capabilities. Collectively, this paper enriches the current understanding of sentiment analysis, providing valuable insights and guidance for the selection of suitable methods by marketing researchers and practitioners in the age of Generative AI."
}
"""