version: '3.8'

services:
  pubtator3-mcp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # APT mirror configuration (comment out to use default)
        APT_MIRROR: ${APT_MIRROR:-http://mirrors.aliyun.com}
        # PIP mirror configuration (comment out to use default)
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST:-pypi.tuna.tsinghua.edu.cn}
    container_name: pubtator3-mcp-server
    ports:
      - "8991:8991"
    environment:
      - PYTHONPATH=/app
      - PORT=8991
      - PYTHONUNBUFFERED=1
      # Mirror configuration for runtime (if needed)
      - APT_MIRROR=${APT_MIRROR:-http://mirrors.aliyun.com}
      - PIP_INDEX_URL=${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
      - PIP_TRUSTED_HOST=${PIP_TRUSTED_HOST:-pypi.tuna.tsinghua.edu.cn}
    volumes:
      - ./src:/app/src  # Hot reload: mount source code
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8991/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pubtator3-network

networks:
  pubtator3-network:
    driver: bridge

