version: '3.8'

services:
  mcp-server:
    build: .
    environment:
      - LOG_LEVEL=info
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  logs:
    driver: local 