version: '3.8'

services:
  pubchempy-fastmcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989"  # FastMCP HTTP server port
    environment:
      - PYTHONPATH=/app
      - PORT=8989
    volumes:
      - ./src:/app/src  # Hot reload: mount source code
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - fastmcp-network

networks:
  fastmcp-network:
    driver: bridge 