version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_CN_MIRRORS=${USE_CN_MIRRORS:-true}
    environment:
      - LOG_LEVEL=info
      - PYTHONPATH=/app
      - USE_CN_MIRRORS=${USE_CN_MIRRORS:-true}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  logs:
    driver: local 